### ISSUE TITLE
Intents issue

### ISSUE THREAD

**Issue by infamouskoala** [blakeando/Discord-Message-Cleaner-selfbot#5]
![image](https://user-images.githubusercontent.com/75808182/218244478-32930f38-cf8b-40d3-bff5-62ce783daeac.png)
This issue occurs everytime i try to make or use a selfbot. It wont let me run it without adding intents and after i add intents, it shows me that the token is invalid because it is ow supposed to be a bot token with intent permissions that a normal user wont have on discord. I am just stuck.

**Comment by xpierroz** [comment]
just use the default intents

**Comment by infamouskoala** [comment]
> just use the default intents

Intents aren't a thing in user accounts

**Comment by xpierroz** [comment]
basically the normal discord library doesn't support anymore self bot, so if you wanna use this outdated tool, you should change to a new selfbot library.
